export default {
  SET_CONFIG: 'SET_CONFIG',
  PAGINATION_SET_PAGE_NUMBER: 'PAGINATION_SET_PAGE_NUMBER',
  PAGINATION_INITIALIZE_PAGINATOR: 'PAGINATION_INITIALIZE_PAGINATOR',
  SET_WEB3_CONFIG: 'SET_WEB3_CONFIG',
  SET_WEB3_STATUS: 'SET_WEB3_STATUS',
  SET_WEB3_SELECTION: 'SET_WEB3_SELECTION',
  SET_WEB3_BROWSER_AVAILABILITY: 'SET_WEB3_BROWSER_AVAILABILITY',
  SET_WEB3: 'SET_WEB3',
  SET_CHAIN_METADATA: 'SET_CHAIN_METADATA',
  // index meta
  SET_EMPTY_INDEX_META: 'SET_EMPTY_INDEX_META',
  SET_INDEX_META_LOADED: 'SET_INDEX_META_LOADED',
  SET_PACKAGE_DB_ADDRESS: 'SET_PACKAGE_DB_ADDRESS',
  SET_RELEASE_DB_ADDRESS: 'SET_RELEASE_DB_ADDRESS',
  SET_NUM_PACKAGES: 'SET_NUM_PACKAGES',
  SET_NUM_RELEASES: 'SET_NUM_RELEASES',
  // index data
  SET_EMPTY_INDEX_DATA: 'SET_EMPTY_INDEX_DATA',
  SET_INDEX_DATA_LOADED: 'SET_INDEX_DATA_LOADED',
  // package meta
  SET_EMPTY_PACKAGE_META: 'SET_EMPTY_PACKAGE_META',
  SET_PACKAGE_META: 'SET_PACKAGE_META',
  SET_PACKAGE_META_LOADED: 'SET_PACKAGE_META_LOADED',
}
