export default {
  SET_CONFIG: 'SET_CONFIG',
  PAGINATION_SET_PAGE_NUMBER: 'PAGINATION_SET_PAGE_NUMBER',
  PAGINATION_INITIALIZE_PAGINATOR: 'PAGINATION_INITIALIZE_PAGINATOR',
  SET_WEB3_CONFIG: 'SET_WEB3_CONFIG',
  SET_WEB3_STATUS: 'SET_WEB3_STATUS',
  SET_WEB3_SELECTION: 'SET_WEB3_SELECTION',
  SET_WEB3_BROWSER_AVAILABILITY: 'SET_WEB3_BROWSER_AVAILABILITY',
  SET_WEB3: 'SET_WEB3',
  SET_CHAIN_METADATA: 'SET_CHAIN_METADATA',
  // index meta
  SET_EMPTY_INDEX_DATA: 'SET_EMPTY_INDEX_DATA',
  SET_PACKAGE_DB_ADDRESS: 'SET_PACKAGE_DB_ADDRESS',
  SET_RELEASE_DB_ADDRESS: 'SET_RELEASE_DB_ADDRESS',
  SET_NUM_PACKAGES: 'SET_NUM_PACKAGES',
  SET_TOTAL_NUM_RELEASES: 'SET_TOTAL_NUM_RELEASES',
  // package list
  SET_PACKAGE_NAME: 'SET_PACKAGE_NAME',
  // package data
  SET_PACKAGE_DATA: 'SET_PACKAGE_DATA',
  // release list
  SET_RELEASE_HASH: 'SET_RELEASE_HASH',
  // release data
  SET_RELEASE_DATA: 'SET_RELEASE_DATA',
  // Thing Setter
  SET_THING: 'SET_THING'
}
